title: Teachings of the Living Prophets - Practicum Project
description: The Practicum Project for the Teachings of the Living Prophets course
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
repository: bitblitobvimormon/TofLP
url: "https://bitblitobvimormon.github.io"
baseurl: "/TofLP"
